// client pages 
export { default as Home } from "./Home/Home"
export { default as About } from "./About/About"
export { default as Resume } from "./Resume/Resume"
export { default as Services } from "./Services/Services"
export { default as Skills } from "./Skills/Skills"
export { default as Projects } from "./Projects/Projects"
export { default as Blogs } from "./Blogs/Blogs"
export { default as Freelancing } from "./Freelancing/Freelancing"
export { default as Testimonials } from "./Testimonials/Testimonials"
export { default as Contact } from "./Contact/Contact"
export { default as Footer } from "./Footer/Footer"
// export { default as Login} from "./Auth/Login"
export { default as Login} from "./Auth/Login"
export { default as Register} from "./Auth/Register"
export { default as Account } from "./Account/Account"