
export const GET_PORTFOLIO_CONTENT = 'GET_PORTFOLIO_CONTENT'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const START_PORTFOLIO_LOADING = 'START_PORTFOLIO_LOADING'
export const END_PORTFOLIO_LOADING = 'END_PORTFOLIO_LOADING'
export const ERROR = 'ERROR'

export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE'
export const GET_ALL_SUBSCRIBERS = 'GET_ALL_SUBSCRIBERS'
export const GET_ALL_ADMINS = 'GET_ALL_ADMINS'
export const GET_ALL_USERS = 'GET_ALL_USERS'

export const CREATE_PEOPLE_FIRST_DOCUMENT = 'CREATE_PEOPLE_FIRST_DOCUMENT'
export const UPDATE_MAIN_ADMIN = 'UPDATE_MAIN_ADMIN'
export const ADD_ADMIN = 'ADD_ADMIN'
export const UPDATE_ADMIN = 'UPDATE_ADMIN'
export const DELETE_ADMIN = 'DELETE_ADMIN'

export const SUBSCRIBE = 'SUBSCRIBE'
export const UNSUBSCRIBE = 'UNSUBSCRIBE'

export const FORM_SUBMIT = 'FORM_SUBMIT'

export const SEND_OTP = 'SEND_OTP'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const DELETE_USER = 'DELETE_USER'