
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const ERROR = 'ERROR'
export const DELETE_SECTION = 'DELETE_SECTION'
export const UPDATE = 'UPDATE'
export const BASE_URL = 'http://localhost:5000'


export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const BUTTON = 'BUTTON'
export const IMAGE = 'IMAGE'

export const GET_ABOUT_CONTENT = 'GET_ABOUT_CONTENT'
export const CREATE_ABOUT_FIRST_DOCUMENT = 'CREATE_ABOUT_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_DOB = 'UPDATE_DOB'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_SUB_TEXT = 'UPDATE_SUB_TEXT'
export const ADD_ABOUT_BUTTON = 'ADD_ABOUT_BUTTON'
export const UPDATE_ABOUT_BUTTON = 'UPDATE_ABOUT_BUTTON'
export const DELETE_ABOUT_BUTTON = 'DELETE_ABOUT_BUTTON'
export const ADD_ABOUT_IMAGE = 'ADD_ABOUT_IMAGE'
export const DELETE_ABOUT_IMAGE = 'DELETE_ABOUT_IMAGE'





export const GET_BLOGS_CONTENT = 'GET_BLOGS_CONTENT'
export const CREATE_BLOGS_FIRST_DOCUMENT = 'CREATE_BLOGS_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_BLOG = 'ADD_BLOG'
export const UPDATE_BLOG = 'UPDATE_BLOG'
export const ADD_BLOG_IMAGE = 'ADD_BLOG_IMAGE'
export const DELETE_BLOG_IMAGE = 'DELETE_BLOG_IMAGE'
export const DELETE_BLOG = 'DELETE_BLOG'


export const GET_CONTACT_CONTENT = 'GET_CONTACT_CONTENT'
export const CREATE_CONTACT_FIRST_DOCUMENT = 'CREATE_CONTACT_FIRST_DOCUMENT'
export const ADD_CONTACT_CARD = 'ADD_CONTACT_CARD'
export const UPDATE_CONTACT_CARD = 'UPDATE_CONTACT_CARD'
export const DELETE_CONTACT_CARD = 'DELETE_CONTACT_CARD'
export const UPDATE_INPUTS = 'UPDATE_INPUTS'


export const GET_FOOTER_CONTENT = 'GET_FOOTER_CONTENT'
export const CREATE_FOOTER_FIRST_DOCUMENT = 'CREATE_FOOTER_FIRST_DOCUMENT'
export const UPDATE_ABOUT_TITLE = 'UPDATE_ABOUT_TITLE'
export const UPDATE_ABOUT_DETAIL = 'UPDATE_ABOUT_DETAIL'
export const UPDATE_LINKS_TITLE = 'UPDATE_LINKS_TITLE'
export const ADD_FOOTER_LINK = 'ADD_FOOTER_LINK'
export const UPDATE_FOOTER_LINK = 'UPDATE_FOOTER_LINK'
export const DELETE_FOOTER_LINK = 'DELETE_FOOTER_LINK'
export const UPDATE_SERVICES_TITLE = 'UPDATE_SERVICES_TITLE'
export const ADD_FOOTER_SERVICE = 'ADD_FOOTER_SERVICE'
export const UPDATE_FOOTER_SERVICE = 'UPDATE_FOOTER_SERVICE'
export const DELETE_FOOTER_SERVICE = 'DELETE_FOOTER_SERVICE'
export const UPDATE_CONTACT_TITLE = 'UPDATE_CONTACT_TITLE'
export const ADD_FOOTER_CONTACT = 'ADD_FOOTER_CONTACT'
export const UPDATE_FOOTER_CONTACT = 'UPDATE_FOOTER_CONTACT'
export const DELETE_FOOTER_CONTACT = 'DELETE_FOOTER_CONTACT'
export const UPDATE_COPYRIGHT = 'UPDATE_COPYRIGHT'
export const DELETE_FOOTER_SECTION = 'DELETE_FOOTER_SECTION'


export const GET_FREELANCING_CONTENT = 'GET_FREELANCING_CONTENT'
export const CREATE_FREELANCING_FIRST_DOCUMENT = 'CREATE_FREELANCING_FIRST_DOCUMENT'
export const UPDATE_FREELANCING_HEADING = 'UPDATE_HEADING'
export const UPDATE_FREELANCING_DETAIL = 'UPDATE_DETAIL'
export const ADD_FEATURE_CARD = 'ADD_FEATURE_CARD'
export const UPDATE_FEATURE_CARD = 'UPDATE_FEATURE_CARD'
export const DELETE_FEATURE_CARD = 'DELETE_FEATURE_CARD'
export const ADD_FREELANCING_CARD = 'ADD_FREELANCING_CARD'
export const UPDATE_FREELANCING_CARD_TITLE = 'UPDATE_FREELANCING_CARD_TITLE'
export const UPDATE_FREELANCING_CARD_DETAIL = 'UPDATE_FREELANCING_CARD_DETAIL'
export const UPDATE_FREELANCING_CARD = 'UPDATE_FREELANCING_CARD'
export const ADD_SUB_FREELANCING_CARD = 'ADD_SUB_FREELANCING_CARD'
export const UPDATE_SUB_FREELANCING_CARD = 'UPDATE_SUB_FREELANCING_CARD'
export const DELETE_SUB_FREELANCING_CARD = 'DELETE_SUB_FREELANCING_CARD'
export const ADD_BUTTON = 'ADD_BUTTON'
export const UPDATE_BUTTON = 'UPDATE_BUTTON'
export const DELETE_BUTTON = 'DELETE_BUTTON'





export const GET_HOME_CONTENT = 'GET_HOME_CONTENT'
export const CREATE_HOME_FIRST_DOCUMENT = 'CREATE_HOME_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const UPDATE_HELLO_TEXT = 'UPDATE_HELLO_TEXT'
export const UPDATE_HEADING_1 = 'UPDATE_HEADING_1'
export const UPDATE_HEADING_2 = 'UPDATE_HEADING_2'
export const UPDATE_SUB_HEADING_1 = 'UPDATE_SUB_HEADING_1'
export const ADD_HOME_IMAGE = 'ADD_HOME_IMAGE'
export const DELETE_HOME_IMAGE = 'DELETE_HOME_IMAGE'
export const ADD_HOME_BUTTON = 'ADD_HOME_BUTTON'
export const UPDATE_HOME_BUTTON = 'UPDATE_HOME_BUTTON'
export const DELETE_HOME_BUTTON = 'DELETE_HOME_BUTTON'







export const GET_NAVBAR_CONTENT = 'GET_NAVBAR_CONTENT'
export const CREATE_NAVBAR_FIRST_DOCUMENT = 'CREATE_NAVBAR_FIRST_DOCUMENT'
export const UPDATE_LOGO = 'UPDATE_LOGO'
export const ADD_NAV_LINK = 'ADD_NAV_LINK'
export const UPDATE_NAV_LINK = 'UPDATE_NAV_LINK'
export const UPDATE_NAV_LINK_NAME = 'UPDATE_NAV_LINK_NAME'
export const UPDATE_NAV_LINK_LINK = 'UPDATE_NAV_LINK_LINK'
export const DELETE_NAV_LINK = 'DELETE_NAV_LINK'
export const ADD_SOCIAL_MEDIA = 'ADD_SOCIAL_MEDIA'
export const UPDATE_SOCIAL_MEDIA = 'UPDATE_SOCIAL_MEDIA'
export const UPDATE_SOCIAL_MEDIA_NAME = 'UPDATE_SOCIAL_MEDIA_NAME'
export const UPDATE_SOCIAL_MEDIA_LINK = 'UPDATE_SOCIAL_MEDIA_LINK'
export const DELETE_SOCIAL_MEDIA = 'DELETE_SOCIAL_MEDIA'



export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const LOGIN = 'LOGIN'
export const SEND_OTP = 'SEND_OTP'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const CREATE_PEOPLE_FIRST_DOCUMENT = 'CREATE_PEOPLE_FIRST_DOCUMENT'
export const GET_ALL_SUBSCRIBERS = 'GET_ALL_SUBSCRIBERS'
export const GET_ALL_ADMINS = 'GET_ALL_ADMINS'
export const SUBSCRIBE = 'SUBSCRIBE'
export const UNSUBSCRIBE = 'UNSUBSCRIBE'
export const UPDATE_MAIN_ADMIN = 'UPDATE_MAIN_ADMIN'
export const ADD_ADMIN = 'ADD_ADMIN'
export const UPDATE_ADMIN = 'UPDATE_ADMIN'
export const DELETE_ADMIN = 'DELETE_ADMIN'



export const GET_PROJECTS_CONTENT = 'GET_PROJECTS_CONTENT'
export const CREATE_PROJECTS_FIRST_DOCUMENT = 'CREATE_PROJECTS_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_PROJECT = 'ADD_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const ADD_PROJECT_IMAGE = 'ADD_PROJECT_IMAGE'
export const DELETE_PROJECT_IMAGE = 'DELETE_PROJECT_IMAGE'
export const DELETE_PROJECT = 'DELETE_PROJECT'




export const GET_RESUMES_CONTENT = 'GET_RESUMES_CONTENT'
export const CREATE_RESUMES_FIRST_DOCUMENT = 'CREATE_RESUMES_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_RESUME = 'ADD_RESUME'
export const UPDATE_RESUME = 'UPDATE_RESUME'
export const DELETE_RESUME = 'DELETE_RESUME'
export const ADD_RESUMES_BUTTON = 'ADD_RESUMES_BUTTON'
export const UPDATE_RESUMES_BUTTON = 'UPDATE_RESUMES_BUTTON'
export const DELETE_RESUMES_BUTTON = 'DELETE_RESUMES_BUTTON'





export const GET_SERVICES_CONTENT = 'GET_SERVICES_CONTENT'
export const CREATE_SERVICES_FIRST_DOCUMENT = 'CREATE_SERVICES_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_SERVICE = 'ADD_SERVICE'
export const UPDATE_SERVICE = 'UPDATE_SERVICE'
export const DELETE_SERVICE = 'DELETE_SERVICE'




export const GET_SKILLS_CONTENT = 'GET_SKILLS_CONTENT'
export const CREATE_SKILLS_FIRST_DOCUMENT = 'CREATE_SKILLS_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_SKILL = 'ADD_SKILL'
export const UPDATE_SKILL = 'UPDATE_SKILL'
export const DELETE_SKILL = 'DELETE_SKILL'




export const GET_TESTIMONIALS_CONTENT = 'GET_TESTIMONIALS_CONTENT'
export const CREATE_TESTIMONIALS_FIRST_DOCUMENT = 'CREATE_TESTIMONIALS_FIRST_DOCUMENT'
// export const UPDATE_FORWARD_HEADING = 'UPDATE_FORWARD_HEADING'
// export const UPDATE_BACK_HEADING = 'UPDATE_BACK_HEADING'
// export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const ADD_TESTIMONIAL = 'ADD_TESTIMONIAL'
export const UPDATE_TESTIMONIAL = 'UPDATE_TESTIMONIAL'
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL'